export const categoryOptions = [
  { value: "Array", label: "Array" },
  { value: "Matrix", label: "Matrix" },
  { value: "String", label: "String" },
  { value: "Hash Table", label: "Hash Table" },
  { value: "Dynamic Programming", label: "Dynamic Programming" },
  { value: "Math", label: "Math" },
  { value: "Sorting", label: "Sorting" },
  { value: "Greedy", label: "Greedy" },
  { value: "Depth-First Search", label: "Depth-First Search" },
  { value: "Database", label: "Database" },
  { value: "Breadth-First Search", label: "Breadth-First Search" },
  { value: "Tree", label: "Tree" },
  { value: "Binary Search", label: "Binary Search" },
  { value: "Matrix", label: "Matrix" },
  { value: "Binary Tree", label: "Binary Tree" },
  { value: "Two Pointers", label: "Two Pointers" },
  { value: "Bit Manipulation", label: "Bit Manipulation" },
  { value: "Stack", label: "Stack" },
  { value: "Design", label: "Design" },
  { value: "Graph", label: "Graph" },
  { value: "Prefix Sum", label: "Prefix Sum" },
  { value: "Backtracking", label: "Backtracking" },
  { value: "Sliding window", label: "Sliding window" },
  { value: "Queue", label: "Queue" },
  { value: "Bitmask", label: "Bitmask" },
  { value: "Memoization", label: "Memoization" },
  { value: "Linked List", label: "Linked List" },
  { value: "Union Find", label: "Union Find" },
];

export const difficultyOptions = [
  { value: "Easy", label: "Easy" },
  { value: "Medium", label: "Medium" },
  { value: "Hard", label: "Hard" },
];
